// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  notification: {
    feed: {
      list: createApiLeaf<"query", typeof import("../functions/notification/feed").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/notification/feed").list>("notification/feed:list"), { auth: "required", type: "query" }),
      markAllRead: createApiLeaf<"mutation", typeof import("../functions/notification/feed").markAllRead>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/feed").markAllRead>("notification/feed:markAllRead"), { auth: "required", type: "mutation" }),
      markRead: createApiLeaf<"mutation", typeof import("../functions/notification/feed").markRead>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/feed").markRead>("notification/feed:markRead"), { auth: "required", type: "mutation" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/notification/feed").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/feed").remove>("notification/feed:remove"), { auth: "required", type: "mutation" }),
      removeAll: createApiLeaf<"mutation", typeof import("../functions/notification/feed").removeAll>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/feed").removeAll>("notification/feed:removeAll"), { auth: "required", type: "mutation" }),
    },
    settings: {
      setPreference: createApiLeaf<"mutation", typeof import("../functions/notification/settings").setPreference>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/settings").setPreference>("notification/settings:setPreference"), { auth: "required", type: "mutation" }),
      status: createApiLeaf<"query", typeof import("../functions/notification/settings").status>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/notification/settings").status>("notification/settings:status"), { auth: "required", type: "query" }),
      upsertDevice: createApiLeaf<"mutation", typeof import("../functions/notification/settings").upsertDevice>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/notification/settings").upsertDevice>("notification/settings:upsertDevice"), { auth: "required", type: "mutation" }),
    },
  },
  organization: {
    profile: {
      generateUploadUrl: createApiLeaf<"mutation", typeof import("../functions/organization/profile").generateUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization/profile").generateUploadUrl>("organization/profile:generateUploadUrl"), { auth: "required", type: "mutation" }),
      get: createApiLeaf<"query", typeof import("../functions/organization/profile").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization/profile").get>("organization/profile:get"), { auth: "required", type: "query" }),
      upsert: createApiLeaf<"mutation", typeof import("../functions/organization/profile").upsert>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization/profile").upsert>("organization/profile:upsert"), { auth: "required", type: "mutation" }),
    },
  },
  payment: {
    charge: {
      createCharge: createApiLeaf<"action", typeof import("../functions/payment/charge").createCharge>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/payment/charge").createCharge>("payment/charge:createCharge"), { auth: "required", type: "action" }),
      getCheckoutContext: createApiLeaf<"query", typeof import("../functions/payment/charge").getCheckoutContext>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/charge").getCheckoutContext>("payment/charge:getCheckoutContext"), { auth: "required", type: "query" }),
      getPendingCharge: createApiLeaf<"query", typeof import("../functions/payment/charge").getPendingCharge>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/charge").getPendingCharge>("payment/charge:getPendingCharge"), { auth: "required", type: "query" }),
      listMine: createApiLeaf<"query", typeof import("../functions/payment/charge").listMine>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/charge").listMine>("payment/charge:listMine"), { auth: "required", type: "query" }),
      simulatePayment: createApiLeaf<"mutation", typeof import("../functions/payment/charge").simulatePayment>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/payment/charge").simulatePayment>("payment/charge:simulatePayment"), { auth: "required", type: "mutation" }),
    },
    dashboard: {
      getOverview: createApiLeaf<"query", typeof import("../functions/payment/dashboard").getOverview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/dashboard").getOverview>("payment/dashboard:getOverview"), { auth: "required", type: "query" }),
      getRevenueSeries: createApiLeaf<"query", typeof import("../functions/payment/dashboard").getRevenueSeries>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/dashboard").getRevenueSeries>("payment/dashboard:getRevenueSeries"), { auth: "required", type: "query" }),
    },
    onboarding: {
      getStatus: createApiLeaf<"query", typeof import("../functions/payment/onboarding").getStatus>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/onboarding").getStatus>("payment/onboarding:getStatus"), { auth: "required", type: "query" }),
      start: createApiLeaf<"action", typeof import("../functions/payment/onboarding").start>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/payment/onboarding").start>("payment/onboarding:start"), { auth: "required", type: "action" }),
    },
    webhook: {
      handleWooviWebhook: createApiLeaf<"mutation", typeof import("../functions/payment/webhook").handleWooviWebhook>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/payment/webhook").handleWooviWebhook>("payment/webhook:handleWooviWebhook"), { type: "mutation" }),
    },
    withdraw: {
      getBalance: createApiLeaf<"query", typeof import("../functions/payment/withdraw").getBalance>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/payment/withdraw").getBalance>("payment/withdraw:getBalance"), { auth: "required", type: "query" }),
      requestWithdraw: createApiLeaf<"action", typeof import("../functions/payment/withdraw").requestWithdraw>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/payment/withdraw").requestWithdraw>("payment/withdraw:requestWithdraw"), { auth: "required", type: "action" }),
    },
  },
  pendings: {
    dismiss: {
      dismiss: createApiLeaf<"mutation", typeof import("../functions/pendings/dismiss").dismiss>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/pendings/dismiss").dismiss>("pendings/dismiss:dismiss"), { auth: "required", type: "mutation" }),
    },
    list: {
      list: createApiLeaf<"query", typeof import("../functions/pendings/list").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/pendings/list").list>("pendings/list:list"), { auth: "required", type: "query" }),
    },
  },
  player: {
    dashboard: {
      getOverview: createApiLeaf<"query", typeof import("../functions/player/dashboard").getOverview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/player/dashboard").getOverview>("player/dashboard:getOverview"), { auth: "required", type: "query" }),
    },
    profile: {
      generateUploadUrl: createApiLeaf<"mutation", typeof import("../functions/player/profile").generateUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/player/profile").generateUploadUrl>("player/profile:generateUploadUrl"), { auth: "required", type: "mutation" }),
      get: createApiLeaf<"query", typeof import("../functions/player/profile").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/player/profile").get>("player/profile:get"), { auth: "required", type: "query" }),
      upsert: createApiLeaf<"mutation", typeof import("../functions/player/profile").upsert>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/player/profile").upsert>("player/profile:upsert"), { auth: "required", type: "mutation" }),
    },
  },
  tournament: {
    bracket: {
      draw: createApiLeaf<"mutation", typeof import("../functions/tournament/bracket").draw>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/bracket").draw>("tournament/bracket:draw"), { auth: "required", type: "mutation" }),
      listBracket: createApiLeaf<"query", typeof import("../functions/tournament/bracket").listBracket>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/bracket").listBracket>("tournament/bracket:listBracket"), { auth: "required", type: "query" }),
      start: createApiLeaf<"mutation", typeof import("../functions/tournament/bracket").start>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/bracket").start>("tournament/bracket:start"), { auth: "required", type: "mutation" }),
      swapSlots: createApiLeaf<"mutation", typeof import("../functions/tournament/bracket").swapSlots>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/bracket").swapSlots>("tournament/bracket:swapSlots"), { auth: "required", type: "mutation" }),
    },
    discovery: {
      getById: createApiLeaf<"query", typeof import("../functions/tournament/discovery").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/discovery").getById>("tournament/discovery:getById"), { auth: "required", type: "query" }),
      listAvailable: createApiLeaf<"query", typeof import("../functions/tournament/discovery").listAvailable>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/discovery").listAvailable>("tournament/discovery:listAvailable"), { auth: "required", type: "query" }),
      listParticipating: createApiLeaf<"query", typeof import("../functions/tournament/discovery").listParticipating>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/discovery").listParticipating>("tournament/discovery:listParticipating"), { auth: "required", type: "query" }),
    },
    entries: {
      approve: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").approve>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").approve>("tournament/entries:approve"), { auth: "required", type: "mutation" }),
      cancel: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").cancel>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").cancel>("tournament/entries:cancel"), { auth: "required", type: "mutation" }),
      create: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").create>("tournament/entries:create"), { auth: "required", type: "mutation" }),
      listForTournament: createApiLeaf<"query", typeof import("../functions/tournament/entries").listForTournament>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/entries").listForTournament>("tournament/entries:listForTournament"), { auth: "required", type: "query" }),
      reject: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").reject>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").reject>("tournament/entries:reject"), { auth: "required", type: "mutation" }),
      respondPartnerInvite: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").respondPartnerInvite>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").respondPartnerInvite>("tournament/entries:respondPartnerInvite"), { auth: "required", type: "mutation" }),
      setEntryRound: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").setEntryRound>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").setEntryRound>("tournament/entries:setEntryRound"), { auth: "required", type: "mutation" }),
      setSeed: createApiLeaf<"mutation", typeof import("../functions/tournament/entries").setSeed>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/entries").setSeed>("tournament/entries:setSeed"), { auth: "required", type: "mutation" }),
    },
    lifecycle: {
      cancel: createApiLeaf<"mutation", typeof import("../functions/tournament/lifecycle").cancel>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/lifecycle").cancel>("tournament/lifecycle:cancel"), { auth: "required", type: "mutation" }),
      conclude: createApiLeaf<"mutation", typeof import("../functions/tournament/lifecycle").conclude>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/lifecycle").conclude>("tournament/lifecycle:conclude"), { auth: "required", type: "mutation" }),
    },
    management: {
      create: createApiLeaf<"mutation", typeof import("../functions/tournament/management").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/management").create>("tournament/management:create"), { auth: "required", type: "mutation" }),
      generateUploadUrl: createApiLeaf<"mutation", typeof import("../functions/tournament/management").generateUploadUrl>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/management").generateUploadUrl>("tournament/management:generateUploadUrl"), { auth: "required", type: "mutation" }),
      getById: createApiLeaf<"query", typeof import("../functions/tournament/management").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/management").getById>("tournament/management:getById"), { auth: "required", type: "query" }),
      listMine: createApiLeaf<"query", typeof import("../functions/tournament/management").listMine>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/management").listMine>("tournament/management:listMine"), { auth: "required", type: "query" }),
      publish: createApiLeaf<"mutation", typeof import("../functions/tournament/management").publish>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/management").publish>("tournament/management:publish"), { auth: "required", type: "mutation" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/tournament/management").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/management").remove>("tournament/management:remove"), { auth: "required", type: "mutation" }),
      update: createApiLeaf<"mutation", typeof import("../functions/tournament/management").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/management").update>("tournament/management:update"), { auth: "required", type: "mutation" }),
    },
    matches: {
      editResult: createApiLeaf<"mutation", typeof import("../functions/tournament/matches").editResult>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/matches").editResult>("tournament/matches:editResult"), { auth: "required", type: "mutation" }),
      listForTournament: createApiLeaf<"query", typeof import("../functions/tournament/matches").listForTournament>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/matches").listForTournament>("tournament/matches:listForTournament"), { auth: "required", type: "query" }),
      listOccupiedSlots: createApiLeaf<"query", typeof import("../functions/tournament/matches").listOccupiedSlots>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/matches").listOccupiedSlots>("tournament/matches:listOccupiedSlots"), { auth: "required", type: "query" }),
      publishResult: createApiLeaf<"mutation", typeof import("../functions/tournament/matches").publishResult>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/matches").publishResult>("tournament/matches:publishResult"), { auth: "required", type: "mutation" }),
      scheduleMatch: createApiLeaf<"mutation", typeof import("../functions/tournament/matches").scheduleMatch>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tournament/matches").scheduleMatch>("tournament/matches:scheduleMatch"), { auth: "required", type: "mutation" }),
    },
    players: {
      searchByUsername: createApiLeaf<"query", typeof import("../functions/tournament/players").searchByUsername>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tournament/players").searchByUsername>("tournament/players:searchByUsername"), { auth: "required", type: "query" }),
    },
  },
  viewer: {
    context: {
      activateOrganization: createApiLeaf<"mutation", typeof import("../functions/viewer/context").activateOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/viewer/context").activateOrganization>("viewer/context:activateOrganization"), { auth: "required", type: "mutation" }),
      get: createApiLeaf<"query", typeof import("../functions/viewer/context").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/viewer/context").get>("viewer/context:get"), { auth: "required", type: "query" }),
      setActiveActor: createApiLeaf<"mutation", typeof import("../functions/viewer/context").setActiveActor>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/viewer/context").setActiveActor>("viewer/context:setActiveActor"), { auth: "required", type: "mutation" }),
    },
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
    'payment.handleWooviWebhook': { path: "/api/webhooks/woovi", method: "POST" },
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
