// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  league: {
    discovery: {
      getById: createApiLeaf<"query", typeof import("../functions/league/discovery").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/discovery").getById>("league/discovery:getById"), { auth: "required", type: "query" }),
      listAvailable: createApiLeaf<"query", typeof import("../functions/league/discovery").listAvailable>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/discovery").listAvailable>("league/discovery:listAvailable"), { auth: "required", type: "query" }),
    },
    management: {
      create: createApiLeaf<"mutation", typeof import("../functions/league/management").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").create>("league/management:create"), { auth: "required", type: "mutation" }),
      getById: createApiLeaf<"query", typeof import("../functions/league/management").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/management").getById>("league/management:getById"), { auth: "required", type: "query" }),
      listMine: createApiLeaf<"query", typeof import("../functions/league/management").listMine>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/management").listMine>("league/management:listMine"), { auth: "required", type: "query" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/league/management").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").remove>("league/management:remove"), { auth: "required", type: "mutation" }),
      update: createApiLeaf<"mutation", typeof import("../functions/league/management").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").update>("league/management:update"), { auth: "required", type: "mutation" }),
    },
    membership: {
      approve: createApiLeaf<"mutation", typeof import("../functions/league/membership").approve>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").approve>("league/membership:approve"), { auth: "required", type: "mutation" }),
      getOverview: createApiLeaf<"query", typeof import("../functions/league/membership").getOverview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/membership").getOverview>("league/membership:getOverview"), { auth: "required", type: "query" }),
      reject: createApiLeaf<"mutation", typeof import("../functions/league/membership").reject>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").reject>("league/membership:reject"), { auth: "required", type: "mutation" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/league/membership").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").remove>("league/membership:remove"), { auth: "required", type: "mutation" }),
      reorderRanking: createApiLeaf<"mutation", typeof import("../functions/league/membership").reorderRanking>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").reorderRanking>("league/membership:reorderRanking"), { auth: "required", type: "mutation" }),
      requestJoin: createApiLeaf<"mutation", typeof import("../functions/league/membership").requestJoin>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").requestJoin>("league/membership:requestJoin"), { auth: "required", type: "mutation" }),
    },
  },
  player: {
    profile: {
      get: createApiLeaf<"query", typeof import("../functions/player/profile").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/player/profile").get>("player/profile:get"), { auth: "required", type: "query" }),
      upsert: createApiLeaf<"mutation", typeof import("../functions/player/profile").upsert>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/player/profile").upsert>("player/profile:upsert"), { auth: "required", type: "mutation" }),
    },
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
