// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  league: {
    challenges: {
      acceptProposal: createApiLeaf<"mutation", typeof import("../functions/league/challenges").acceptProposal>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").acceptProposal>("league/challenges:acceptProposal"), { auth: "required", type: "mutation" }),
      adminManage: createApiLeaf<"mutation", typeof import("../functions/league/challenges").adminManage>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").adminManage>("league/challenges:adminManage"), { auth: "required", type: "mutation" }),
      cancel: createApiLeaf<"mutation", typeof import("../functions/league/challenges").cancel>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").cancel>("league/challenges:cancel"), { auth: "required", type: "mutation" }),
      confirmResult: createApiLeaf<"mutation", typeof import("../functions/league/challenges").confirmResult>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").confirmResult>("league/challenges:confirmResult"), { auth: "required", type: "mutation" }),
      counterPropose: createApiLeaf<"mutation", typeof import("../functions/league/challenges").counterPropose>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").counterPropose>("league/challenges:counterPropose"), { auth: "required", type: "mutation" }),
      create: createApiLeaf<"mutation", typeof import("../functions/league/challenges").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").create>("league/challenges:create"), { auth: "required", type: "mutation" }),
      declineProposal: createApiLeaf<"mutation", typeof import("../functions/league/challenges").declineProposal>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").declineProposal>("league/challenges:declineProposal"), { auth: "required", type: "mutation" }),
      getById: createApiLeaf<"query", typeof import("../functions/league/challenges").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/challenges").getById>("league/challenges:getById"), { auth: "required", type: "query" }),
      listForLeague: createApiLeaf<"query", typeof import("../functions/league/challenges").listForLeague>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/challenges").listForLeague>("league/challenges:listForLeague"), { auth: "required", type: "query" }),
      listOccupiedSlots: createApiLeaf<"query", typeof import("../functions/league/challenges").listOccupiedSlots>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/challenges").listOccupiedSlots>("league/challenges:listOccupiedSlots"), { auth: "required", type: "query" }),
      requestCancellation: createApiLeaf<"mutation", typeof import("../functions/league/challenges").requestCancellation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").requestCancellation>("league/challenges:requestCancellation"), { auth: "required", type: "mutation" }),
      respondCancellationRequest: createApiLeaf<"mutation", typeof import("../functions/league/challenges").respondCancellationRequest>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").respondCancellationRequest>("league/challenges:respondCancellationRequest"), { auth: "required", type: "mutation" }),
      reviewChallenge: createApiLeaf<"mutation", typeof import("../functions/league/challenges").reviewChallenge>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").reviewChallenge>("league/challenges:reviewChallenge"), { auth: "required", type: "mutation" }),
      reviewResult: createApiLeaf<"mutation", typeof import("../functions/league/challenges").reviewResult>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").reviewResult>("league/challenges:reviewResult"), { auth: "required", type: "mutation" }),
      submitResult: createApiLeaf<"mutation", typeof import("../functions/league/challenges").submitResult>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/challenges").submitResult>("league/challenges:submitResult"), { auth: "required", type: "mutation" }),
    },
    discovery: {
      getById: createApiLeaf<"query", typeof import("../functions/league/discovery").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/discovery").getById>("league/discovery:getById"), { auth: "required", type: "query" }),
      listAvailable: createApiLeaf<"query", typeof import("../functions/league/discovery").listAvailable>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/discovery").listAvailable>("league/discovery:listAvailable"), { auth: "required", type: "query" }),
    },
    management: {
      create: createApiLeaf<"mutation", typeof import("../functions/league/management").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").create>("league/management:create"), { auth: "required", type: "mutation" }),
      getById: createApiLeaf<"query", typeof import("../functions/league/management").getById>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/management").getById>("league/management:getById"), { auth: "required", type: "query" }),
      listMine: createApiLeaf<"query", typeof import("../functions/league/management").listMine>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/management").listMine>("league/management:listMine"), { auth: "required", type: "query" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/league/management").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").remove>("league/management:remove"), { auth: "required", type: "mutation" }),
      update: createApiLeaf<"mutation", typeof import("../functions/league/management").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/management").update>("league/management:update"), { auth: "required", type: "mutation" }),
    },
    membership: {
      approve: createApiLeaf<"mutation", typeof import("../functions/league/membership").approve>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").approve>("league/membership:approve"), { auth: "required", type: "mutation" }),
      getOverview: createApiLeaf<"query", typeof import("../functions/league/membership").getOverview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/league/membership").getOverview>("league/membership:getOverview"), { auth: "required", type: "query" }),
      reject: createApiLeaf<"mutation", typeof import("../functions/league/membership").reject>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").reject>("league/membership:reject"), { auth: "required", type: "mutation" }),
      remove: createApiLeaf<"mutation", typeof import("../functions/league/membership").remove>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").remove>("league/membership:remove"), { auth: "required", type: "mutation" }),
      reorderRanking: createApiLeaf<"mutation", typeof import("../functions/league/membership").reorderRanking>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").reorderRanking>("league/membership:reorderRanking"), { auth: "required", type: "mutation" }),
      requestJoin: createApiLeaf<"mutation", typeof import("../functions/league/membership").requestJoin>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/league/membership").requestJoin>("league/membership:requestJoin"), { auth: "required", type: "mutation" }),
    },
  },
  player: {
    profile: {
      get: createApiLeaf<"query", typeof import("../functions/player/profile").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/player/profile").get>("player/profile:get"), { auth: "required", type: "query" }),
      upsert: createApiLeaf<"mutation", typeof import("../functions/player/profile").upsert>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/player/profile").upsert>("player/profile:upsert"), { auth: "required", type: "mutation" }),
    },
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
