export const NOTIFICATION_EVENT_TYPES = [
  "tournament.partner.invited",
  "tournament.partner.responded",
  "tournament.partner.awaiting_reply",
  "tournament.partner.invite_cancelled",
  "tournament.entry.created",
  "tournament.entry.confirmed",
  "tournament.entry.rejected",
  "tournament.entry.cancelled",
  "tournament.entry.refund_requested",
  "tournament.entry.refunded",
  "tournament.bracket.published",
  "tournament.bracket.placement_failed",
  "tournament.match.ready",
  "tournament.match.reassigned",
  "tournament.match.schedule_declined",
  "tournament.match.schedule_cancelled",
  "tournament.match.schedule_proposed",
  "tournament.match.scheduled",
  "tournament.match.rescheduled",
  "tournament.match.result",
  "tournament.match.result_edited",
  "tournament.match.score_declined",
  "tournament.match.score_cancelled",
  "tournament.match.score_proposed",
  "tournament.finished",
  "tournament.cancelled",
] as const;

export type NotificationEventType = (typeof NOTIFICATION_EVENT_TYPES)[number];
