// biome-ignore-all format: generated
// This file is auto-generated by kitcn migrate create.
// Do not edit manually.

import { defineMigrationSet } from 'kitcn/orm';
import { migration as migration_0 } from "./20260504_181921_remove_player_profile_display_name";
import { migration as migration_1 } from "./20260505_000001_remove_player_profile_category_and_photo_url";

export const migrations = defineMigrationSet([
  migration_0,
  migration_1,
]);
