// biome-ignore-all format: generated
// This file is auto-generated by kitcn migrate create.
// Do not edit manually.

import { defineMigrationSet } from 'kitcn/orm';
import { migration as migration_0 } from './20260504_181921_remove_player_profile_display_name';
import { migration as migration_1 } from './20260505_000001_remove_player_profile_category_and_photo_url';
import { migration as migration_2 } from './20260509_000001_remove_player_profile_legacy_fields';
import { migration as migration_3 } from './20260619_000001_purge_player_profile_pii';
import { migration as migration_4 } from './20260814_163103_backfill_withdrawals_fee_status';
import { migration as migration_5 } from './20260916_103007_clear_entry_seed_phase';
import { migration as migration_6 } from './20260917_221648_backfill_team_member_count';
import { migration as migration_7 } from './20260920_091746_backfill_tournament_entry_slots';
import { migration as migration_8 } from './20260921_191850_add_pending_dismissal';
import { migration as migration_9 } from './20260926_113435_backfill_refund_recovery_status';

export const migrations = defineMigrationSet([
  migration_0,
  migration_1,
  migration_2,
  migration_3,
  migration_4,
  migration_5,
  migration_6,
  migration_7,
  migration_8,
  migration_9,
]);
